### ISSUE TITLE
Fossology rdf file: Error converting: Error converting SPDX file: class org.spdx.library.model.SpdxInvalidTypeExceptionIncompatible type for property licenseInfoInFile: class org.spdx.library.model.license.AnyLicenseInfo

### ISSUE THREAD

**Issue by dineshr93** [spdx/tools-java#16]
tools-java-0.0.6-jar-with-dependencies.jar
 https://bintray.com/spdx/spdx-tools/tools-java#files/org%2Fspdx%2Ftools-java%2F0.0.6

Input file with .rdf extension(fossology generated rdf file): [acl-2.2.52-20210326-1035-SPDX.rdf.txt](https://github.com/spdx/tools-java/files/6303592/acl-2.2.52-20210326-1035-SPDX.rdf.txt)  (added txt as git doesnt support rdf file format uploads)

Command:
`D:\spdx-java>java -jar tools-java-0.0.6-jar-with-dependencies.jar Convert acl-2.2.52-20210326-1035-SPDX.rdf a.tag`

Output File with partial generated text: [a.tag.txt](https://github.com/spdx/tools-java/files/6303593/a.tag.txt) (added txt as git doesnt support tag file format uploads)

Error Text:

![image](https://user-images.githubusercontent.com/4498415/114550502-8fe7e700-9c62-11eb-9112-a1fdc5ee3a32.png)

1. How to resolve this?
2. is tag file a yml format? if not how to generate spdx in yml format?
Thanks

**Comment by dineshr93** [comment]
Also I checked verify command on the fossology rdf 

```
D:\spdx-java>java -jar tools-java-0.0.6-jar-with-dependencies.jar Verify acl-2.2.52-20210326-1035-SPDX.rdf
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
Exception in thread "main" java.lang.RuntimeException: org.spdx.library.model.SpdxInvalidTypeException: No enumeration was found for URI http://spdx.org/licenses/NOASSERTION for type class org.spdx.library.model.license.AnyLicenseInfo
        at org.spdx.library.model.ModelCollection.checkConvertTypedValue(ModelCollection.java:167)
        at org.spdx.library.model.ModelCollection.access$000(ModelCollection.java:47)
        at org.spdx.library.model.ModelCollection$ModelCollectionIterator.next(ModelCollection.java:72)
        at org.spdx.library.model.ModelObject.verifyCollection(ModelObject.java:966)
        at org.spdx.library.model.SpdxItem._verify(SpdxItem.java:206)
        at org.spdx.library.model.SpdxFile._verify(SpdxFile.java:274)
        at org.spdx.library.model.ModelObject.verify(ModelObject.java:176)
        at org.spdx.library.model.SpdxPackage._verify(SpdxPackage.java:557)
        at org.spdx.library.model.ModelObject.verify(ModelObject.java:176)
        at org.spdx.library.model.Relationship._verify(Relationship.java:86)
        at org.spdx.library.model.ModelObject.verify(ModelObject.java:176)
        at org.spdx.library.model.ModelObject.verifyCollection(ModelObject.java:967)
        at org.spdx.library.model.SpdxElement._verify(SpdxElement.java:105)
        at org.spdx.library.model.SpdxDocument._verify(SpdxDocument.java:243)
        at org.spdx.library.model.ModelObject.verify(ModelObject.java:176)
        at org.spdx.library.model.ModelObject.verify(ModelObject.java:184)
        at org.spdx.tools.Verify.verify(Verify.java:132)
        at org.spdx.tools.Verify.main(Verify.java:70)
        at org.spdx.tools.Main.main(Main.java:50)
Caused by: org.spdx.library.model.SpdxInvalidTypeException: No enumeration was found for URI http://spdx.org/licenses/NOASSERTION for type class org.spdx.library.model.license.AnyLicenseInfo
        at org.spdx.library.model.ModelCollection.checkConvertTypedValue(ModelCollection.java:159)
        ... 18 more

D:\spdx-java>

Is fossology rdf outdated?

```

**Comment by goneall** [comment]
@dineshr93 From the stack trace, the RDF file should have the URI for NOASSERTION be `http://spdx.org/rdf/terms#noassertion` rather than `http://spdx.org/licenses/NOASSERTION`.

I think I recall the old SPDX libraries may have been using the incorrect licenses/NOASSERTION.

We could handle the incorrectly specified license NOASSERTION values in the library, but my preference would be to correct the application that generated the RDF/XML.

BTW - the same issue probably exists for the NONE license.

**Comment by goneall** [comment]
Closing this issue as it seems to be an issue with the old library and the software that generated the SPDX file
