### ISSUE TITLE
Doesn't even work with provided examples

### ISSUE THREAD

**Issue by gitgitwhat** [spdx/tools-java#84]
This tool, and even the online version, fail with the provided SPDX samples found here(https://github.com/spdx/tools-python/tree/main/data).  

Trying to verify the RDX example using this command `java -jar tools-java-1.1.2-SNAPSHOT-jar-with-dependencies.jar Verify spdx.rdf` causes this error:

```
23:10:21.232 [main] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 159 column 128): Invalid byte 1 of 1-byte UTF-8 sequence.
Exception in thread "main" org.apache.jena.shared.JenaException: org.xml.sax.SAXParseException; lineNumber: 159; columnNumber: 128; Invalid byte 1 of 1-byte UTF-8 sequence.
        at org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler.fatalError(RDFDefaultErrorHandler.java:62)
        at org.apache.jena.rdfxml.xmlinput.impl.ARPSaxErrorHandler.fatalError(ARPSaxErrorHandler.java:47)
        at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.warning(XMLHandler.java:199)
        at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.fatalError(XMLHandler.java:229)
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:181)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:306)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3085)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at org.apache.jena.rdfxml.xmlinput.impl.RDFXMLParser.parse(RDFXMLParser.java:95)
        at org.apache.jena.rdfxml.xmlinput.JenaReader.read(JenaReader.java:163)
        at org.apache.jena.rdfxml.xmlinput.JenaReader.read(JenaReader.java:152)
        at org.apache.jena.rdfxml.xmlinput.JenaReader.read(JenaReader.java:221)
        at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:253)
        at org.spdx.spdxRdfStore.RdfStore.deSerialize(RdfStore.java:523)
        at org.spdx.tools.Verify.verify(Verify.java:128)
        at org.spdx.tools.Verify.main(Verify.java:80)
        at org.spdx.tools.Main.main(Main.java:52)
Caused by: org.xml.sax.SAXParseException; lineNumber: 159; columnNumber: 128; Invalid byte 1 of 1-byte UTF-8 sequence.
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
        ... 20 more
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
        at java.xml/com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:702)
        at java.xml/com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:568)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1699)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanContent(XMLEntityScanner.java:1052)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanContent(XMLDocumentFragmentScannerImpl.java:1555)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2846)
        ... 17 more

```

Meanwhile trying to verify the same RDX file online throws this error:

`Cannot invoke "String.equals(Object)" because the return value of "org.apache.jena.rdf.model.Resource.getURI()" is null`

Trying the other example files throw other errors.  The fact that both the CLI tool and the online verifier fail indicate that either the examples are incorrect or something is really busted with the tools.

**Comment by goneall** [comment]
Thanks @gitgitwhat for reporting this - especially with all the details.

I wasn't able the first issue on my local machine, but I was able to duplicate the second issue when you ran it for the online tools.

From reading the error on the first issue, it looks like it is an encoding error.  According the spec, the files need to be encoded as UTF-8.  It looks like the file is encoded in some other format.  You can try importing it into an editor like Notepad++ and convert the encoding.

On the second issue, there is an NPE in one of the library dependencies.  I'll create a pull request for a fix.

Once you get past the NPE, you'll run into some additional problems which I believe are issues with the source.  Here's my output from the verify using the tools-java:

```
17:09:21.691 [main] ERROR org.apache.jena.util.JenaXMLInput - Problem setting StAX property - name: "http://javax.xml.XMLConstants/property/accessExternalDTD" - value: "" - error: Unrecognized property 'http://javax.xml.XMLConstants/property/accessExternalDTD'
17:09:22.328 [main] ERROR org.spdx.library.model.SpdxElement - Could not find or create the external document reference for document namespace http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301
17:09:22.349 [main] ERROR org.spdx.library.model.SpdxElement - Could not find or create the external document reference for document namespace http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301
This SPDX Document is not valid due to:
	Relationship error: Error getting related SPDX element for relationship: Could not find or create the external document reference for document namespace http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301 in Sample_Document-V2.1
	Invalid license id '__anon__0089126e-c2ae-4ff9-9bf5-7370a232e5c9'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
	Invalid license id '__anon__30ba0e50-a314-434f-b28d-030f87677d8f'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
	Invalid license id '__anon__d85b36d4-31b9-4d4a-a034-3301f293cafc'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
	Invalid license id '__anon__e519273b-97d9-4d59-84d3-9b07223f4176'.  Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.
	Document must have at least one relationship of type DOCUMENT_DESCRIBES
```

**Comment by goneall** [comment]
I created a [pull request in the SPDX Java RDF store](https://github.com/spdx/spdx-java-rdf-store/pull/39) which should fix issue number 2 mentioned above.

I'm going to transfer this issue back to the Python libraries for issue number one and the additional issues I flagged above.  These appear to be issues with the example files and not issues with the Java tools.
